import asyncio
import logging
import re
from typing import Any, Dict, List, Optional

from fastapi import APIRouter, HTTPException, Query, WebSocket, WebSocketDisconnect
from pydantic import BaseModel, Field

from app.config import settings
from app.graph.nodes import query_cache
from app.graph.workflow import run_intent_report, run_refresh_agent, run_replay_agent
from app.services.report_service import report_service
from app.services.session_store import session_store

logger = logging.getLogger(__name__)
router = APIRouter()

# Matches messages that are purely a filter/sort action on existing data
# e.g. "filter by location LOC001", "show only completed", "narrow to Q1"
_FILTER_REDIRECT_RE = re.compile(
    r"^\s*(filter\s+(by|to|for)|show\s+only|narrow\s+(by|to)|only\s+show|sort\s+by|group\s+by)\b",
    re.IGNORECASE,
)

# Matches explicit row-count requests: "top 10", "first 5", "bottom 20"
# Deliberately excludes "last N" — usually means a time period ("last 30 days").
_TOP_N_RE = re.compile(r"\b(?:top|first|bottom)\s+(\d+)\b", re.IGNORECASE)


def _extract_user_limit(query: str) -> int:
    """Return the explicit N from 'top N' / 'first N' / 'bottom N', else 0."""
    m = _TOP_N_RE.search(query)
    return int(m.group(1)) if m else 0

_FILTER_REDIRECT_MSG = (
    "Use the filter controls above the results to narrow down the data — "
    "no need to re-run the report. "
    "Your full result set is already loaded and filters apply instantly."
)

# ─────────────────────────────────────────────────────────────────────────────
# Existing models (unchanged)
# ─────────────────────────────────────────────────────────────────────────────

class QueryRequest(BaseModel):
    query: str = Field(..., description="Natural language question about the KRA data")

    class Config:
        json_schema_extra = {
            "example": {
                "query": "Show all active KRAs with employee names and current progress"
            }
        }


class QueryResponse(BaseModel):
    # Intent outcome — lets frontend handle off_topic / clarification_needed gracefully
    status: str = Field("success", description="success | off_topic | clarification_needed | error")
    message: Optional[str] = Field(None, description="Populated for off_topic responses")
    suggestions: Optional[List[str]] = Field(None, description="Example prompts (off_topic only)")
    follow_up_question: Optional[str] = Field(None, description="Clarification question (clarification_needed only)")
    follow_up_options: Optional[List[str]] = Field(None, description="Answer options for follow-up question")

    # SQL result fields
    sql_query: Optional[str] = Field(None, description="Generated MySQL SELECT statement")
    explanation: Optional[str] = Field(None, description="One-sentence description of what the query returns")
    dimensions: List[str] = Field(default_factory=list)
    recommended_column_filters: List[str] = Field(default_factory=list)
    data: List[Dict[str, Any]] = Field(default_factory=list)
    row_count: int = Field(0)
    execution_time: float = Field(0.0)
    error: Optional[str] = Field(None)
    cache_hit: bool = Field(False)

    # Session ID — use with /report/refresh/{session_id} and /report/stream/{session_id}
    session_id: Optional[str] = Field(None, description="Use this for refresh/stream endpoints")


# ─────────────────────────────────────────────────────────────────────────────
# Intent-aware endpoint models
# ─────────────────────────────────────────────────────────────────────────────

class GenerateRequest(BaseModel):
    query: str = Field(..., description="Natural language question about KRA data")
    user_id: str = Field("demo_user", description="User identifier")
    user_role: str = Field(
        "employee",
        description="Role of the requesting user: employee | lead | manager | hr",
    )
    chat_session_id: str = Field(
        "",
        description=(
            "Conversation-level session ID generated by the frontend at chat-start. "
            "All queries within the same chat window must send the same value. "
            "This scopes conversation memory and follow-up detection to a single session. "
            "When omitted the system falls back to user-id-only memory (legacy behaviour)."
        ),
    )
    page: int = Field(1, ge=1, description="Page number (1-based)")
    page_size: int = Field(
        0,
        ge=0,
        description="Rows per page (0 = use server default, max capped by MAX_PAGE_SIZE)",
    )
    has_data: bool = Field(
        False,
        description=(
            "Set to True when the frontend already has a result set displayed. "
            "Enables client-side filter redirect: if the query is a pure filter action "
            "(e.g. 'filter by location X'), the agent will redirect to UI controls "
            "instead of re-running the report."
        ),
    )

    class Config:
        json_schema_extra = {
            "example": {
                "query": "show my goals", "user_id": "user_42",
                "user_role": "employee", "chat_session_id": "sess_abc123",
                "page": 1, "page_size": 1000, "has_data": False,
            }
        }


class ReplayRequest(BaseModel):
    sql_query: str = Field(..., description="The saved SQL query to re-execute against live data")
    user_id: str = Field("demo_user", description="User identifier")
    user_role: str = Field("employee", description="Role of the requesting user")
    page: int = Field(1, ge=1)
    page_size: int = Field(0, ge=0, description="Rows per page (0 = server default)")


class ReportResponse(BaseModel):
    status: str = Field(..., description="greeting | off_topic | filter_redirect | clarification_needed | success | error")

    # Greeting / off-topic / clarification
    message: Optional[str] = None
    suggestions: Optional[List[str]] = None

    # Clarification (relationship_type == "uncertain")
    follow_up_question: Optional[str] = Field(None, description="Clarification question when relationship is ambiguous")
    follow_up_options: Optional[List[str]] = Field(None, description="Suggested answer options for clarification")

    # Success
    enriched_prompt: Optional[str] = None
    sql_query: Optional[str] = None
    explanation: Optional[str] = None
    dimensions: Optional[List[str]] = None
    recommended_column_filters: Optional[List[str]] = None
    data: Optional[List[Dict[str, Any]]] = None
    row_count: Optional[int] = None
    execution_time: Optional[float] = None
    error: Optional[str] = None
    cache_hit: Optional[bool] = None

    # Client-side filter metadata — returned with every data response
    filterable_columns: Optional[List[Dict[str, Any]]] = Field(
        None,
        description=(
            "Columns the frontend can filter on. Each entry has: "
            "column, label, filter_type (categorical|date_range|text_search|numeric_range), values."
        ),
    )
    filter_instruction: Optional[str] = Field(
        None, description="Always 'client_side_only' — filters never trigger a new SQL execution."
    )
    llm_call_on_filter: Optional[bool] = Field(
        None, description="Always false — applying a filter must not trigger a new LLM call."
    )

    # Pagination metadata (present on success responses)
    page: Optional[int] = None
    page_size: Optional[int] = None
    total_rows: Optional[int] = None
    total_pages: Optional[int] = None
    has_next_page: Optional[bool] = None
    has_prev_page: Optional[bool] = None

    # Refresh metadata
    refresh_mode: Optional[bool] = None
    refreshed_at: Optional[str] = None

    # Error codes (SESSION_EXPIRED | ACCESS_DENIED | SCHEMA_CHANGED)
    error_code: Optional[str] = None

    # Always present
    session_id: str = Field(...)


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _build_report_response(
    status: str,
    result: Dict[str, Any],
    session_id: str,
    original_prompt: str,
) -> ReportResponse:
    if status == "greeting":
        return ReportResponse(
            status="greeting",
            message=result.get("message", ""),
            session_id=session_id,
        )
    if status == "off_topic":
        return ReportResponse(
            status="off_topic",
            message=result.get("message", ""),
            session_id=session_id,
        )
    if status == "clarification_needed":
        return ReportResponse(
            status="clarification_needed",
            message=result.get("follow_up_question") or result.get("message", ""),
            follow_up_question=result.get("follow_up_question"),
            follow_up_options=result.get("follow_up_options", []),
            session_id=session_id,
        )
    # success (may carry an error field if SQL execution failed)
    return ReportResponse(
        status="success",
        enriched_prompt=result.get("enriched_prompt", ""),
        sql_query=result.get("sql_query"),
        explanation=result.get("explanation"),
        dimensions=result.get("dimensions", []),
        recommended_column_filters=result.get("recommended_column_filters", []),
        filterable_columns=result.get("filterable_columns", []),
        filter_instruction=result.get("filter_instruction", "client_side_only"),
        llm_call_on_filter=result.get("llm_call_on_filter", False),
        data=result.get("data", []),
        row_count=result.get("row_count", 0),
        execution_time=result.get("execution_time", 0.0),
        error=result.get("error"),
        cache_hit=result.get("cache_hit", False),
        page=result.get("page", 1),
        page_size=result.get("page_size", settings.PAGE_SIZE),
        total_rows=result.get("total_rows", result.get("row_count", 0)),
        total_pages=result.get("total_pages", 1),
        has_next_page=result.get("has_next_page", False),
        has_prev_page=result.get("has_prev_page", False),
        session_id=session_id,
    )


# ─────────────────────────────────────────────────────────────────────────────
# Existing endpoint (unchanged behaviour)
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/query",
    response_model=QueryResponse,
    summary="Natural Language → SQL → Result",
    description=(
        "Submit a plain-English question. The AI agent:\n\n"
        "1. Converts it to a MySQL SELECT via **GPT-4o-mini**\n"
        "2. Validates the SQL (safety + LIMIT enforcement)\n"
        "3. Executes it against the **vthink_kra** database\n"
        "4. Returns results with `dimensions` and `recommended_column_filters`"
    ),
)
async def run_query(request: QueryRequest):
    try:
        # Create a session so validated SQL is cached in Redis,
        # enabling /report/refresh and /report/stream for this query.
        session_id = session_store.create({
            "original_prompt": request.query,
            "user_id": "demo_user",
            "user_role": "employee",
        })

        result = await report_service.generate(
            user_id="demo_user",
            query=request.query,
            debug=False,
            session_id=session_id,
        )

        status = result.get("status", "success")
        return QueryResponse(
            status=status,
            message=result.get("message"),
            suggestions=result.get("suggestions"),
            follow_up_question=result.get("follow_up_question"),
            follow_up_options=result.get("follow_up_options"),
            sql_query=result.get("sql_query"),
            explanation=result.get("explanation"),
            dimensions=result.get("dimensions", []),
            recommended_column_filters=result.get("recommended_column_filters", []),
            data=result.get("data", []),
            row_count=result.get("row_count", 0),
            execution_time=result.get("execution_time", 0.0),
            error=result.get("error"),
            cache_hit=result.get("cache_hit", False),
            session_id=session_id,
        )
    except Exception as exc:
        logger.exception(f"query error: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ─────────────────────────────────────────────────────────────────────────────
# Intent-aware endpoints
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/report/generate",
    response_model=ReportResponse,
    summary="Intent-Aware Report Generation",
    description=(
        "Submit a natural language query. Returns one of:\n\n"
        "- **greeting** — social/conversational opener; warm reply + report suggestion\n"
        "- **off_topic** — unrelated to KRA; polite decline + redirect\n"
        "- **success** — SQL executed, data returned\n\n"
        "The returned `session_id` enables "
        "`/report/refresh/{session_id}` and `/report/stream/{session_id}`."
    ),
)
async def generate_report(request: GenerateRequest) -> ReportResponse:
    try:
        session_id = session_store.create({
            "original_prompt": request.query,
            "user_id": request.user_id,
            "user_role": request.user_role,
        })

        # Short-circuit: if the frontend has data loaded and the user is asking
        # to filter/sort via chat, redirect them to the UI filter controls.
        # No LLM call, no SQL execution — the result set is already in the browser.
        if request.has_data and _FILTER_REDIRECT_RE.match(request.query):
            logger.info(
                f"[generate] filter_redirect user={request.user_id} "
                f"query={request.query[:60]!r}"
            )
            return ReportResponse(
                status="filter_redirect",
                message=_FILTER_REDIRECT_MSG,
                session_id=session_id,
            )

        user_limit = _extract_user_limit(request.query)
        effective_page_size = user_limit if user_limit > 0 else (request.page_size or settings.PAGE_SIZE)

        result = await run_intent_report(
            user_id=request.user_id,
            query=request.query,
            user_role=request.user_role,
            session_id=session_id,
            chat_session_id=request.chat_session_id,
            page=request.page,
            page_size=effective_page_size,
        )

        # Enforce top-N: cap the result to exactly N rows and show LIMIT N in the SQL.
        logger.info(f"[generate] user_limit={user_limit} status={result.get('status')} data_rows={len(result.get('data') or [])}")
        if user_limit > 0 and result.get("status") not in ("clarification_needed", "greeting", "off_topic"):
            data = result.get("data") or []
            if len(data) > user_limit:
                result["data"] = data[:user_limit]
                result["row_count"] = user_limit
                result["total_rows"] = user_limit
                result["total_pages"] = 1
                result["has_next_page"] = False
            sql_q = result.get("sql_query") or ""
            if sql_q and not re.search(r"\bLIMIT\b", sql_q, re.IGNORECASE):
                result["sql_query"] = f"{sql_q} LIMIT {user_limit}"
            logger.info(f"[generate] after top-N cap: data_rows={len(result.get('data') or [])} sql_has_limit={'LIMIT' in (result.get('sql_query') or '').upper()}")

        status = result.get("status", "success")
        logger.info(f"[generate] user={request.user_id} status={status} session={session_id}")
        return _build_report_response(status, result, session_id, request.query)

    except Exception as exc:
        logger.exception(f"[generate] error: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


@router.post(
    "/report/replay",
    response_model=ReportResponse,
    summary="Re-execute a saved report query for live data",
    description=(
        "Accepts a saved SQL query and re-executes it against the live MySQL database. "
        "No LLM or prompt building — the query is re-validated for safety then executed directly. "
        "Use this when loading a saved report to guarantee fresh data instead of cached/stale results."
    ),
)
async def replay_report(request: ReplayRequest) -> ReportResponse:
    try:
        if not request.sql_query.strip():
            raise HTTPException(status_code=400, detail="sql_query must not be empty")

        result = await run_replay_agent(
            sql_query=request.sql_query,
            user_id=request.user_id,
            user_role=request.user_role,
            page=request.page,
            page_size=request.page_size,
        )

        session_id = session_store.create({
            "original_prompt": f"[replay] {request.sql_query[:120]}",
            "user_id": request.user_id,
            "user_role": request.user_role,
        })

        status = result.get("status", "success")
        if status == "error":
            return ReportResponse(
                status="error",
                error=result.get("error"),
                session_id=session_id,
            )

        logger.info(
            f"[replay] user={request.user_id} rows={result.get('row_count', 0)} "
            f"session={session_id}"
        )
        return ReportResponse(
            status="success",
            sql_query=result.get("sql_query"),
            explanation=result.get("explanation", ""),
            dimensions=result.get("dimensions", []),
            recommended_column_filters=result.get("recommended_column_filters", []),
            filterable_columns=result.get("filterable_columns", []),
            filter_instruction="client_side_only",
            llm_call_on_filter=False,
            data=result.get("data", []),
            row_count=result.get("row_count", 0),
            execution_time=result.get("execution_time", 0.0),
            page=result.get("page", 1),
            page_size=result.get("page_size", settings.PAGE_SIZE),
            total_rows=result.get("total_rows", 0),
            total_pages=result.get("total_pages", 1),
            has_next_page=result.get("has_next_page", False),
            has_prev_page=result.get("has_prev_page", False),
            refresh_mode=True,
            refreshed_at=result.get("refreshed_at"),
            session_id=session_id,
        )
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception(f"[replay] error: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ─────────────────────────────────────────────────────────────────────────────
# HTTP polling refresh (single cycle)
# ─────────────────────────────────────────────────────────────────────────────

@router.get(
    "/report/refresh/{session_id}",
    response_model=ReportResponse,
    summary="Single-Cycle Report Refresh (HTTP Polling)",
    description=(
        "Executes the cached SQL directly — no LLM, no validator, no RBAC re-evaluation.\n\n"
        "**Error codes returned as HTTP status:**\n"
        "- `404 SESSION_EXPIRED` — cache missing or TTL expired\n"
        "- `403 ACCESS_DENIED` — user_id does not match session owner\n"
        "- `409 SCHEMA_CHANGED` — schema drift detected; stale cache deleted"
    ),
)
async def refresh_report(
    session_id: str,
    user_id: str = Query(..., description="Must match the user_id from /report/generate"),
    user_role: str = Query("employee"),
    page: int = Query(1, ge=1, description="Page number to refresh (default 1)"),
    page_size: int = Query(0, ge=0, description="Rows per page (0 = server default)"),
) -> ReportResponse:
    try:
        result = await run_refresh_agent(session_id=session_id, user_id=user_id, page=page, page_size=page_size)
        error_code = result.get("error_code")

        if error_code == "SESSION_EXPIRED":
            raise HTTPException(status_code=404, detail="SESSION_EXPIRED: Please regenerate the report.")
        if error_code == "ACCESS_DENIED":
            raise HTTPException(status_code=403, detail="ACCESS_DENIED: User does not match session owner.")
        if error_code == "SCHEMA_CHANGED":
            raise HTTPException(status_code=409, detail="SCHEMA_CHANGED: Schema has changed. Please regenerate.")
        if error_code:
            raise HTTPException(status_code=500, detail=result.get("message", error_code))

        return ReportResponse(
            status=result.get("status", "success"),
            explanation=result.get("explanation"),
            dimensions=result.get("dimensions", []),
            recommended_column_filters=result.get("recommended_column_filters", []),
            data=result.get("data", []),
            row_count=result.get("row_count", 0),
            execution_time=result.get("execution_time", 0.0),
            error=result.get("error"),
            refresh_mode=True,
            refreshed_at=result.get("refreshed_at"),
            page=result.get("page", page),
            page_size=result.get("page_size", settings.PAGE_SIZE),
            total_rows=result.get("total_rows", result.get("row_count", 0)),
            total_pages=result.get("total_pages", 1),
            has_next_page=result.get("has_next_page", False),
            has_prev_page=result.get("has_prev_page", False),
            session_id=session_id,
        )
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception(f"[refresh] error session={session_id}: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ─────────────────────────────────────────────────────────────────────────────
# Pagination — fetch a specific page of a previously generated report
# ─────────────────────────────────────────────────────────────────────────────

@router.get(
    "/report/page/{session_id}",
    response_model=ReportResponse,
    summary="Fetch a Specific Page of Report Results",
    description=(
        "Re-executes the cached SQL with the requested page offset. "
        "No LLM or validator calls — uses the same security-validated SQL "
        "stored by `/report/generate`.\n\n"
        "**Use `has_next_page` from the previous response to decide whether to call this.**"
    ),
)
async def get_report_page(
    session_id: str,
    user_id: str = Query(..., description="Must match the user_id from /report/generate"),
    page: int = Query(2, ge=1, description="Page number (1-based, must be > 1 for new data)"),
    page_size: int = Query(0, ge=0, description="Rows per page (0 = server default)"),
) -> ReportResponse:
    try:
        result = await run_refresh_agent(
            session_id=session_id,
            user_id=user_id,
            page=page,
            page_size=page_size,
        )
        error_code = result.get("error_code")

        if error_code == "SESSION_EXPIRED":
            raise HTTPException(status_code=404, detail="SESSION_EXPIRED: Please regenerate the report.")
        if error_code == "ACCESS_DENIED":
            raise HTTPException(status_code=403, detail="ACCESS_DENIED: User does not match session owner.")
        if error_code == "SCHEMA_CHANGED":
            raise HTTPException(status_code=409, detail="SCHEMA_CHANGED: Schema has changed. Please regenerate.")
        if error_code:
            raise HTTPException(status_code=500, detail=result.get("message", error_code))

        return ReportResponse(
            status=result.get("status", "success"),
            explanation=result.get("explanation"),
            dimensions=result.get("dimensions", []),
            recommended_column_filters=result.get("recommended_column_filters", []),
            data=result.get("data", []),
            row_count=result.get("row_count", 0),
            execution_time=result.get("execution_time", 0.0),
            page=result.get("page", page),
            page_size=result.get("page_size", settings.PAGE_SIZE),
            total_rows=result.get("total_rows", 0),
            total_pages=result.get("total_pages", 1),
            has_next_page=result.get("has_next_page", False),
            has_prev_page=result.get("has_prev_page", False),
            session_id=session_id,
        )
    except HTTPException:
        raise
    except Exception as exc:
        logger.exception(f"[page] error session={session_id} page={page}: {exc}")
        raise HTTPException(status_code=500, detail=str(exc))


# ─────────────────────────────────────────────────────────────────────────────
# WebSocket streaming (continuous auto-refresh)
# ─────────────────────────────────────────────────────────────────────────────

@router.websocket("/report/stream/{session_id}")
async def stream_report(
    websocket: WebSocket,
    session_id: str,
    user_id: str = Query(...),
    user_role: str = Query("employee"),
    interval: Optional[int] = Query(None, description="Override refresh interval in seconds"),
):
    """
    Streams live refreshed report data over WebSocket.

    - Executes an immediate refresh on connect, then loops every N seconds.
    - Sends the same ReportResponse JSON structure as /report/refresh.
    - Closes cleanly on WebSocketDisconnect, SESSION_EXPIRED, SCHEMA_CHANGED,
      or ACCESS_DENIED — never leaves a dangling async loop.
    """
    await websocket.accept()
    refresh_interval = interval if interval is not None else settings.STREAM_REFRESH_INTERVAL_SECONDS
    logger.info(f"[stream] connected session={session_id[:16]} user={user_id} interval={refresh_interval}s")

    try:
        while True:
            result = await run_refresh_agent(session_id=session_id, user_id=user_id)
            await websocket.send_json(result)

            error_code = result.get("error_code")
            if error_code in ("SESSION_EXPIRED", "SCHEMA_CHANGED", "ACCESS_DENIED"):
                logger.info(f"[stream] terminating session={session_id[:16]} reason={error_code}")
                await websocket.close(code=1008)  # 1008 = Policy Violation
                return

            await asyncio.sleep(refresh_interval)

    except WebSocketDisconnect:
        logger.info(f"[stream] client disconnected session={session_id[:16]} user={user_id}")
    except Exception as exc:
        logger.exception(f"[stream] unexpected error session={session_id[:16]}: {exc}")
        try:
            await websocket.close(code=1011)  # 1011 = Internal Error
        except Exception:
            pass


# ─────────────────────────────────────────────────────────────────────────────
# Cache management endpoints (unchanged)
# ─────────────────────────────────────────────────────────────────────────────

@router.get("/debug/top-n", summary="Debug top-N extraction")
async def debug_top_n(query: str = Query(...)):
    limit = _extract_user_limit(query)
    return {"query": query, "extracted_limit": limit, "code_version": "v2-safety-net"}

@router.get("/cache/stats", summary="Cache statistics")
async def get_cache_stats():
    return query_cache.stats()


@router.delete("/cache", summary="Clear all cached query results")
async def clear_cache():
    cleared = query_cache.clear()
    return {"cleared": cleared, "message": f"Removed {cleared} cached entries"}
